import './globals.css'
import { Roboto } from 'next/font/google'
// import  "bootstrap/dist/css"

const inter = Roboto({weight: ['100', '300', '400', '500', '700', '900'], subsets : [ 'latin']})

export const metadata: any = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = { children : string}

export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
